name: CI/CD for Server

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Чек-аут репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Настройка JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Проверка стиля для всех модулей
      - name: Run style check
        run: mvn validate

      # Сборка JAR
      - name: Build JAR
        run: mvn -B package -DskipTests

      # Получение хэша коммита и даты
      - name: Get commit hash and date
        id: vars
        run: |
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "build_date=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_OUTPUT

      # Переименование JAR
      - name: Rename JAR
        run: |
          mv server/target/server.jar server/target/${{ steps.vars.outputs.commit_hash }}_${{ steps.vars.outputs.build_date }}.jar

      # Выгрузка JAR на helios
      - name: Deploy JAR to Helios
        uses: appleboy/scp-action@v0.1.4
        with:
            host: se.ifmo.ru
            username: s467211
            key: ${{ secrets.HELIOS_SSH_KEY }}
            port: 2222
            source: server/target/${{ steps.vars.outputs.commit_hash }}_${{ steps.vars.outputs.build_date }}.jar
            target: /home/studs/s467211/jars/
            debug: true

